### ISSUE TITLE
Repo not compiling w/o .mbedignore

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/mcr20a-rf-driver#13]
Same issue as with [atmel](https://github.com/ARMmbed/atmel-rf-driver/issues/59) and [stm-spirit1-rf-driver](https://github.com/ARMmbed/stm-spirit1-rf-driver/issues/1), it will not compile unless you include feature nanostack OR use a .mbedignore -file.

@SeppoTakalo

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/mcr20a-rf-driver/pull/14
