### ISSUE TITLE
Driver calls Nanostack from interrupt context.

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/mcr20a-rf-driver#4]
In mbed OS 5, you should not call Nanostack from interrupt context.
Doing so will block other interrupts happening, for example serial port.

This driver needs to be refactored in a similar way how the example Atmel driver had: https://github.com/ARMmbed/atmel-rf-driver/pull/31

**Comment by SeppoTakalo** [comment]
@maclobdell Can you forward the information to NXP if they will fix this?

**Comment by mmahadevan108** [comment]
cc @alinlazar

**Comment by 0xc0170** [comment]
Any update for this issue?

**Comment by SeppoTakalo** [comment]
NXP is working for it.
